services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: $P{POSTGRES_DB}
    volumes:
      - /home/grivvus/docker_volumes/postgres/coursework:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend/
    container_name: coursework_python
    depends_on:
      - db
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/
    restart: on-failure
