"""add name col to product

Revision ID: 0d938e2ad55a
Revises: 8ed2995fd4af
Create Date: 2024-05-06 11:57:57.950455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d938e2ad55a'
down_revision: Union[str, None] = '8ed2995fd4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
