"""chenge column name from product to product_id in feedback

Revision ID: 64e5868ef0fe
Revises: 20a92c11c8b7
Create Date: 2024-05-06 18:11:01.526455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e5868ef0fe'
down_revision: Union[str, None] = '20a92c11c8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('feedback_product_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'product', ['product_id'], ['id'])
    op.drop_column('feedback', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_product_fkey', 'feedback', 'product', ['product'], ['id'])
    op.drop_column('feedback', 'product_id')
    # ### end Alembic commands ###
